<?php

namespace Database\Seeders;



use Gujarat\LocationData\Models\District;
use Gujarat\LocationData\Models\SubDistrict;
use Gujarat\LocationData\Models\Village;
use Illuminate\Database\Seeder;

class VillageSeeder extends Seeder
{
    public function run(): void
    {
        $villages = [
            ["Name" => "Abhepar", "Local Name" => "અભેપર", "Sub District" => "Lodhika"],
            [
                "Name" => "Adbalka",
                "Local Name" => "અડબાલકા",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Adhiya", "Local Name" => "આધિયા", "Sub District" => "Jasdan"],
            [
                "Name" => "Adval",
                "Local Name" => "અડવાળ ",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Ajmer", "Local Name" => "અજમેર", "Sub District" => "Vinchhiya"],
            ["Name" => "Akala", "Local Name" => "અકળા ", "Sub District" => "Jetpur"],
            ["Name" => "Amargadh", "Local Name" => "અમરગઢ", "Sub District" => "Rajkot"],
            [
                "Name" => "Amarnagar",
                "Local Name" => "અમરનગર",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Ambaliala",
                "Local Name" => "અંબાલિયાલા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Ambardi",
                "Local Name" => "આંબરડી ",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Ambardi",
                "Local Name" => "આંબરડી ",
                "Sub District" => "Jasdan",
            ],
            ["Name" => "Amrapar", "Local Name" => "અમરાપર", "Sub District" => "Jetpur"],
            [
                "Name" => "Amrapur",
                "Local Name" => "અમરાપુર",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Amreli",
                "Local Name" => "અમરેલી",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Analgadh", "Local Name" => "અનલગઢ", "Sub District" => "Gondal"],
            [
                "Name" => "Anandpar",
                "Local Name" => "આનંદપર",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Anandpar",
                "Local Name" => "આનંદપર",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Anandpar (Ct)",
                "Local Name" => "આનંદપર (સીટી)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Anchvad",
                "Local Name" => "આંચવાડ ",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Anida",
                "Local Name" => "અનિડા",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Anida", "Local Name" => "અનિડા", "Sub District" => "Gondal"],
            [
                "Name" => "Aniyala",
                "Local Name" => "અનિયાલા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Ankadiya",
                "Local Name" => "આંકડિયા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Arab Timbdi",
                "Local Name" => "અરબ ટીમ્બડી ",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Ardoi",
                "Local Name" => "અરડોઇ",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Arni", "Local Name" => "અરની", "Sub District" => "Upleta"],
            [
                "Name" => "Asalpar",
                "Local Name" => "અસલપુર",
                "Sub District" => "Vinchhiya",
            ],
            ["Name" => "Atkot", "Local Name" => "આટકોટ", "Sub District" => "Jasdan"],
            ["Name" => "Badpar", "Local Name" => "બાદપર", "Sub District" => "Rajkot"],
            [
                "Name" => "Bagdadiya",
                "Local Name" => "બગદડિયા",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Baghi", "Local Name" => "બાઘી", "Sub District" => "Paddhari"],
            [
                "Name" => "Bakhalvad",
                "Local Name" => "બાખલવડ",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Balapar",
                "Local Name" => "બાલાપર",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Baldhoi", "Local Name" => "બલધોઇ", "Sub District" => "Jasdan"],
            ["Name" => "Balsar", "Local Name" => "બલસાર", "Sub District" => "Lodhika"],
            [
                "Name" => "Bamanbore",
                "Local Name" => "બામનબોર",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Bandhali",
                "Local Name" => "બંધાલી",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Bandhiya",
                "Local Name" => "બંધિયા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Bandhiya",
                "Local Name" => "બંધિયા",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Bandra", "Local Name" => "બાંદ્રા", "Sub District" => "Gondal"],
            [
                "Name" => "Bardiya",
                "Local Name" => "બરડિયા",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Barvala", "Local Name" => "બરવાલા", "Sub District" => "Jasdan"],
            ["Name" => "Barvan", "Local Name" => "બારવણ", "Sub District" => "Rajkot"],
            [
                "Name" => "Bava Pipaliya",
                "Local Name" => "બાવા પીપળીયા",
                "Sub District" => "Jetpur",
            ],
            ["Name" => "Bedi", "Local Name" => "બેડી", "Sub District" => "Rajkot"],
            [
                "Name" => "Bedi (Og)",
                "Local Name" => "બેડી (ઓગ)",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Bedla", "Local Name" => "બેડલા", "Sub District" => "Rajkot"],
            ["Name" => "Belda", "Local Name" => "બેલડા", "Sub District" => "Vinchhiya"],
            [
                "Name" => "Belda",
                "Local Name" => "બેલડા",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Betavad", "Local Name" => "બેટાવડ", "Sub District" => "Gondal"],
            [
                "Name" => "Bhadajaliya",
                "Local Name" => "ભડાજલિયા",
                "Sub District" => "Dhoraji",
            ],
            ["Name" => "Bhader", "Local Name" => "ભાદર", "Sub District" => "Dhoraji"],
            ["Name" => "Bhadla", "Local Name" => "ભાડલા", "Sub District" => "Jasdan"],
            ["Name" => "Bhadli", "Local Name" => "ભડલી", "Sub District" => "Jasdan"],
            [
                "Name" => "Bhadoi",
                "Local Name" => "ભદોઈ",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Bhadva",
                "Local Name" => "ભાડ્વ",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Bhandariya",
                "Local Name" => "ભંડારિયા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Bhandariya",
                "Local Name" => "ભંડારિયા",
                "Sub District" => "Jasdan",
            ],
            ["Name" => "Bhangda", "Local Name" => "ભાંગડા", "Sub District" => "Rajkot"],
            ["Name" => "Bhankh", "Local Name" => "ભાંક", "Sub District" => "Upleta"],
            ["Name" => "Bharudi", "Local Name" => "ભરુડી", "Sub District" => "Gondal"],
            ["Name" => "Bhayasar", "Local Name" => "ભાયસર", "Sub District" => "Rajkot"],
            [
                "Name" => "Bhayavadar",
                "Local Name" => "ભાયાવદર",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Bheda Pipaliya",
                "Local Name" => "ભેડા પીપળીયા",
                "Sub District" => "Jetpur",
            ],
            ["Name" => "Bhimora", "Local Name" => "ભીમોરા", "Sub District" => "Upleta"],
            [
                "Name" => "Bhojpara",
                "Local Name" => "ભોજપરા",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Bhola", "Local Name" => "ભોલા", "Sub District" => "Dhoraji"],
            [
                "Name" => "Bholgamda",
                "Local Name" => "ભોલગામડા",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Bhonyra",
                "Local Name" => "ભોયરા",
                "Sub District" => "Vinchhiya",
            ],
            ["Name" => "Bhukhi", "Local Name" => "ભુખી", "Sub District" => "Dhoraji"],
            ["Name" => "Bhunava", "Local Name" => "ભુનાવા", "Sub District" => "Gondal"],
            ["Name" => "Bhupgadh", "Local Name" => "ભૂપગઢ", "Sub District" => "Rajkot"],
            ["Name" => "Bhutvad", "Local Name" => "ભૂતવડ", "Sub District" => "Dhoraji"],
            ["Name" => "Bildi", "Local Name" => "બીલડી", "Sub District" => "Gondal"],
            [
                "Name" => "Biliyala",
                "Local Name" => "બિલિયાલા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Bodi Ghodi",
                "Local Name" => "બોડી ઘોડી",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Boghravadar",
                "Local Name" => "બોઘરાવદર",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Bordi Samadhiyala",
                "Local Name" => "બોરડી સમધિયાળા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Boriya",
                "Local Name" => "બોરિયા",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Champabeda",
                "Local Name" => "ચંપાબેડા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Champrajpur",
                "Local Name" => "ચંપરાજપુર",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Chanchadiya",
                "Local Name" => "ચાંચડિયા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Chandli",
                "Local Name" => "ચાંદલી",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Chanol Moti",
                "Local Name" => "ચાનોલ મોટી ",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Chanol Nani",
                "Local Name" => "ચાનોલ નાની",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Chanol Navi",
                "Local Name" => "ચાનોલ નવી",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Charakhdi",
                "Local Name" => "ચરખડી",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Charaniya",
                "Local Name" => "ચારણીયા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Charan Samadhiyala",
                "Local Name" => "ચરણ સમધિયાળા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Charel",
                "Local Name" => "ચારેલ",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Charelia",
                "Local Name" => "ચારેલિયા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Chavandi",
                "Local Name" => "ચાવંડી",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Chhadvavadar",
                "Local Name" => "છડવાવદર",
                "Sub District" => "Dhoraji",
            ],
            ["Name" => "Chhapra", "Local Name" => "છાપરા", "Sub District" => "Lodhika"],
            [
                "Name" => "Chhasiya",
                "Local Name" => "છાસિયા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Chhatrasa",
                "Local Name" => "છત્રસા",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Chhelli Ghodi",
                "Local Name" => "છેલ્લી ઘોડી",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Chibhda", "Local Name" => "ચિભડા", "Sub District" => "Lodhika"],
            ["Name" => "Chichod", "Local Name" => "ચિચોડ", "Sub District" => "Dhoraji"],
            [
                "Name" => "Chikhalia",
                "Local Name" => "ચીખલીયા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Chitaliya",
                "Local Name" => "ચિતલીયા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Chitravad",
                "Local Name" => "ચિત્રાવડ",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Chitravad Pati",
                "Local Name" => "ચિત્રાવડ પાટી",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Chitravav",
                "Local Name" => "ચિત્રાવવ",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Chordi", "Local Name" => "ચોરડી", "Sub District" => "Gondal"],
            [
                "Name" => "Dadar",
                "Local Name" => "દાદર",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Dadli", "Local Name" => "દાદલી", "Sub District" => "Vinchhiya"],
            [
                "Name" => "Dadva Hamirpara",
                "Local Name" => "દડવા હમીરપારા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Dadvi",
                "Local Name" => "દડવી",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Dahinsara",
                "Local Name" => "દહિંસરા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Dahisarda (Aji)",
                "Local Name" => "દહીસરડા (આજી)",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Dahisarda Und",
                "Local Name" => "દહીસરડા ઉંડ",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Daiya", "Local Name" => "દૈયા", "Sub District" => "Gondal"],
            ["Name" => "Daliya", "Local Name" => "દાલિયા", "Sub District" => "Gondal"],
            ["Name" => "Dedarva", "Local Name" => "દેદરવા", "Sub District" => "Jetpur"],
            [
                "Name" => "Depaliya",
                "Local Name" => "દેપલીયા",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Derdi", "Local Name" => "દેરડી", "Sub District" => "Jetpur"],
            ["Name" => "Derdi", "Local Name" => "દેરડી", "Sub District" => "Gondal"],
            ["Name" => "Deroi", "Local Name" => "ડેરોઈ", "Sub District" => "Rajkot"],
            [
                "Name" => "Detadiya",
                "Local Name" => "દેતાડિયા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Devachadi",
                "Local Name" => "દેવચડી",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Devaliya",
                "Local Name" => "દેવલિયા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Devdhari",
                "Local Name" => "દેવધરી",
                "Sub District" => "Vinchhiya",
            ],
            ["Name" => "Devgam", "Local Name" => "દેવગામ", "Sub District" => "Lodhika"],
            [
                "Name" => "Devki Galol",
                "Local Name" => "દેવકી ગાલોલ",
                "Sub District" => "Jetpur",
            ],
            ["Name" => "Devla", "Local Name" => "દેવળા", "Sub District" => "Gondal"],
            ["Name" => "Devla", "Local Name" => "દેવળા", "Sub District" => "Lodhika"],
            ["Name" => "Devpara", "Local Name" => "દેવપરા", "Sub District" => "Jasdan"],
            [
                "Name" => "Dhamalpar",
                "Local Name" => "ધમાલપર",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Dhandhiya",
                "Local Name" => "ઢાંઢીયા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Dhandhni",
                "Local Name" => "ઢાંઢણી",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Dhank", "Local Name" => "ઢાંક", "Sub District" => "Upleta"],
            ["Name" => "Dharala", "Local Name" => "ધારાલા", "Sub District" => "Gondal"],
            [
                "Name" => "Dhedhuki",
                "Local Name" => "ઢેઢુકી",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Dhokaliya",
                "Local Name" => "ધોકળીયા",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Dholara", "Local Name" => "ઢોલરા", "Sub District" => "Lodhika"],
            [
                "Name" => "Dholidhar",
                "Local Name" => "ઢોલીધર",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Dhoraji",
                "Local Name" => "ધોરાજી",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Dhudashiya",
                "Local Name" => "ધુડાશિયા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Dhudiya Domda",
                "Local Name" => "ધુડિયા દોમડા",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Dhunana Gam",
                "Local Name" => "ધુનાના ગામ",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Dodiyala",
                "Local Name" => "ડોડિયાલા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Dolatpar",
                "Local Name" => "દોલતપર",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Domda Bhayuna",
                "Local Name" => "દોમડા ભયુના",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Dudhivadar",
                "Local Name" => "દુધીવદર",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Dumiyani",
                "Local Name" => "ડુમિયાની",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Dungarka",
                "Local Name" => "ડુંગરકા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Dungarpar",
                "Local Name" => "ડુંગરપાર",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Fadadang",
                "Local Name" => "ફડાડાંગ",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Fareni", "Local Name" => "ફરેની", "Sub District" => "Dhoraji"],
            [
                "Name" => "Fatepar",
                "Local Name" => "ફતેપર",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Fulzar",
                "Local Name" => "ફુલઝાર",
                "Sub District" => "Vinchhiya",
            ],
            ["Name" => "Gadha", "Local Name" => "ગધા", "Sub District" => "Upleta"],
            [
                "Name" => "Gadhadiya (Jam)",
                "Local Name" => "ગઢડિયા (જામ)",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Gadhadiya (Jas)",
                "Local Name" => "ગઢડિયા (જસ)",
                "Sub District" => "Jasdan",
            ],
            ["Name" => "Gadhala", "Local Name" => "ગઢળા", "Sub District" => "Jasdan"],
            ["Name" => "Gadhala", "Local Name" => "ગઢળા", "Sub District" => "Upleta"],
            ["Name" => "Gadhda", "Local Name" => "ગઢડા", "Sub District" => "Paddhari"],
            [
                "Name" => "Gadhethal",
                "Local Name" => "ગધેથલ",
                "Sub District" => "Upleta",
            ],
            ["Name" => "Gadhka", "Local Name" => "ગઢકા", "Sub District" => "Rajkot"],
            ["Name" => "Ganod", "Local Name" => "ગણોદ", "Sub District" => "Upleta"],
            ["Name" => "Garida", "Local Name" => "ગારિડા", "Sub District" => "Rajkot"],
            ["Name" => "Garnala", "Local Name" => "ગરનાલા", "Sub District" => "Gondal"],
            [
                "Name" => "Gavaridad",
                "Local Name" => "ગવરીદાદ",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Ghanteshvar (Ct)",
                "Local Name" => "ઘંટેશ્વર (સીટી)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Ghoghavadar",
                "Local Name" => "ઘોઘાવદર",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Godladhar",
                "Local Name" => "ગોડલાધર",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Gokhlana",
                "Local Name" => "ગોખલાના",
                "Sub District" => "Jasdan",
            ],
            ["Name" => "Golida", "Local Name" => "ગોલિડા", "Sub District" => "Rajkot"],
            ["Name" => "Gomta", "Local Name" => "ગોમટા", "Sub District" => "Gondal"],
            ["Name" => "Gondal", "Local Name" => "ગોંડલ", "Sub District" => "Gondal"],
            [
                "Name" => "Goraiya",
                "Local Name" => "ગોરૈયા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Govindpar",
                "Local Name" => "ગોવિંદપર",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Gunda", "Local Name" => "ગુંડા", "Sub District" => "Rajkot"],
            [
                "Name" => "Gundala",
                "Local Name" => "ગુંદાળા ",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Gundala",
                "Local Name" => "ગુંદાળા ",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Gundala Jam",
                "Local Name" => "ગુંદાળા  જામ",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Gundala (Jas)",
                "Local Name" => "ગુંદાળા  (જસ)",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Gundasara",
                "Local Name" => "ગુંડાસરા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Gundasari",
                "Local Name" => "ગુંડાસરી",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Hadala", "Local Name" => "હડાલા", "Sub District" => "Rajkot"],
            [
                "Name" => "Hadamatala",
                "Local Name" => "હડામટલા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Hadamatala",
                "Local Name" => "હડામટલા",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Hadfodi", "Local Name" => "હડફોડી", "Sub District" => "Upleta"],
            [
                "Name" => "Hadmadiya",
                "Local Name" => "હડમદિયા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Hadmatiya",
                "Local Name" => "હડમતીયા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Hadmatiya",
                "Local Name" => "હડમતીયા",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Hadmatiya (Bedi)",
                "Local Name" => "હડમતિયા (બેદી)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Hadmatiya (Golida)",
                "Local Name" => "હડમતિયા (ગોલિડા)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Hadmatiya Khanda",
                "Local Name" => "હડમતીયા ખાંડા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Halenda",
                "Local Name" => "હેલેન્ડા",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Haripar", "Local Name" => "હરિપર", "Sub District" => "Jetpur"],
            [
                "Name" => "Haripar",
                "Local Name" => "હરિપર",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Haripar", "Local Name" => "હરિપર", "Sub District" => "Rajkot"],
            [
                "Name" => "Haripar Pal",
                "Local Name" => "હરિપર પાલ",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Haripar Taravada",
                "Local Name" => "હરિપર તરવડા",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Hariyasan",
                "Local Name" => "હરિયાસન",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Hariyasan",
                "Local Name" => "હરિયાસન",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Hathasani",
                "Local Name" => "હાથસાની",
                "Sub District" => "Vinchhiya",
            ],
            ["Name" => "Hidad", "Local Name" => "હિદાદ", "Sub District" => "Paddhari"],
            [
                "Name" => "Hingolgadh",
                "Local Name" => "હિંગોલગઢ",
                "Sub District" => "Vinchhiya",
            ],
            ["Name" => "Hirasar", "Local Name" => "હિરાસર", "Sub District" => "Rajkot"],
            [
                "Name" => "Hodthali",
                "Local Name" => "હોડથલી",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Intala Nana",
                "Local Name" => "ઇન્ટાલા નાના",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Ishvariya",
                "Local Name" => "ઈશ્વરિયા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Ishvariya",
                "Local Name" => "ઈશ્વરિયા",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Ishvariya",
                "Local Name" => "ઈશ્વરિયા",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Isra", "Local Name" => "ઇસરા", "Sub District" => "Upleta"],
            ["Name" => "Jal", "Local Name" => "જલ", "Sub District" => "Upleta"],
            ["Name" => "Jaliya", "Local Name" => "જાલિયા", "Sub District" => "Rajkot"],
            [
                "Name" => "Jambudi",
                "Local Name" => "જાંબુડી",
                "Sub District" => "Jetpur",
            ],
            ["Name" => "Jamgadh", "Local Name" => "જામગઢ", "Sub District" => "Rajkot"],
            [
                "Name" => "Jam Kandorna",
                "Local Name" => "જામ કંડોરના",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Jamnavad",
                "Local Name" => "જામનાવડ",
                "Sub District" => "Dhoraji",
            ],
            ["Name" => "Jamvali", "Local Name" => "જામવલી", "Sub District" => "Gondal"],
            [
                "Name" => "Janada",
                "Local Name" => "જનાદા",
                "Sub District" => "Vinchhiya",
            ],
            ["Name" => "Jangvad", "Local Name" => "જંગવડ", "Sub District" => "Jasdan"],
            [
                "Name" => "Jasapar",
                "Local Name" => "જસાપર",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Jasapar", "Local Name" => "જસાપર", "Sub District" => "Jasdan"],
            ["Name" => "Jasdan", "Local Name" => "જસદણ", "Sub District" => "Jasdan"],
            [
                "Name" => "Jashvantpur",
                "Local Name" => "જશવંતપુર",
                "Sub District" => "Lodhika",
            ],
            ["Name" => "Jepur", "Local Name" => "જેપુર", "Sub District" => "Jetpur"],
            [
                "Name" => "Jetakuba",
                "Local Name" => "જેતાકુબા",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Jetalsar (Ct)",
                "Local Name" => "જેતલસર (સીટી)",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Jetalsar (Junction)",
                "Local Name" => "જેતલસર (જંક્શન)",
                "Sub District" => "Jetpur",
            ],
            ["Name" => "Jetpur", "Local Name" => "જેતપુર", "Sub District" => "Jetpur"],
            [
                "Name" => "Jhilariya",
                "Local Name" => "ઝીલારિયા",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Jhiyana", "Local Name" => "ઝિયાના", "Sub District" => "Rajkot"],
            ["Name" => "Jivapar", "Local Name" => "જીવાપર", "Sub District" => "Jasdan"],
            [
                "Name" => "Jivapar",
                "Local Name" => "જીવાપર",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Jivapar (Bamanbore)",
                "Local Name" => "જીવાપર (બામણબોર)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Jodhpar Chhala",
                "Local Name" => "જોધપર છલ્લા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Juna Pipaliya",
                "Local Name" => "જુના પીપળીયા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Juna Rajpipla",
                "Local Name" => "જુના રાજપીપળા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Juni Mengani",
                "Local Name" => "જુની મેંગાની",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Juni Sankali",
                "Local Name" => "જુની સાંકાલી",
                "Sub District" => "Jetpur",
            ],
            ["Name" => "Kaduka", "Local Name" => "કડુકા", "Sub District" => "Jasdan"],
            [
                "Name" => "Kagdadi",
                "Local Name" => "કાગદાદી",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Kagvad", "Local Name" => "કાગવડ", "Sub District" => "Jetpur"],
            [
                "Name" => "Kalambhdi",
                "Local Name" => "કાલંભડી",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Kalana", "Local Name" => "કલાણા", "Sub District" => "Dhoraji"],
            [
                "Name" => "Kalaria",
                "Local Name" => "કાલારિયા",
                "Sub District" => "Upleta",
            ],
            ["Name" => "Kalasar", "Local Name" => "કાલાસર", "Sub District" => "Jasdan"],
            ["Name" => "Kalipat", "Local Name" => "કાલીપટ", "Sub District" => "Rajkot"],
            [
                "Name" => "Kamadhiya",
                "Local Name" => "કામધિયા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Kamarkotda",
                "Local Name" => "કામરકોટડા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Kamlapur",
                "Local Name" => "કમળાપુર",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Kanavadala",
                "Local Name" => "કાનવદલા",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Kandhevaliya",
                "Local Name" => "કાંધેવલિયા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Kanesara",
                "Local Name" => "કનેસરા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Kangashiyali",
                "Local Name" => "કાંગાશિયાલી",
                "Sub District" => "Lodhika",
            ],
            ["Name" => "Kankot", "Local Name" => "કનકોટ", "Sub District" => "Rajkot"],
            ["Name" => "Kanpar", "Local Name" => "કાનપર", "Sub District" => "Jasdan"],
            [
                "Name" => "Kansloliya",
                "Local Name" => "કાંસલોલિયા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Kantoliya",
                "Local Name" => "કંટોલિયા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Karmal Kotda",
                "Local Name" => "કરમલ કોટડા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Kasturbadham",
                "Local Name" => "કસ્તુરબાધામ",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Kathrota",
                "Local Name" => "કાથ્રોટા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Kathrota",
                "Local Name" => "કાથ્રોટા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Kerala",
                "Local Name" => "કેરાળા ",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Kerala", "Local Name" => "કેરાળા ", "Sub District" => "Upleta"],
            ["Name" => "Kerali", "Local Name" => "કેરાલી", "Sub District" => "Jetpur"],
            [
                "Name" => "Keshvala",
                "Local Name" => "કેશવાલા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Khadkana",
                "Local Name" => "ખડકાના",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Khadvavdi",
                "Local Name" => "ખડવવડી",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Khajurda",
                "Local Name" => "ખજુરદા",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Khajurdi",
                "Local Name" => "ખજુર્ડી",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Khajuri Gundala",
                "Local Name" => "ખજુરી ગુંદાલા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Khakhada Bela",
                "Local Name" => "ખાખડા બેલા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Khakhi Jalia",
                "Local Name" => "ખાખી જાલિયા",
                "Sub District" => "Upleta",
            ],
            ["Name" => "Khambha", "Local Name" => "ખાંભા", "Sub District" => "Lodhika"],
            [
                "Name" => "Khambhala",
                "Local Name" => "ખંભલા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Khambhalida",
                "Local Name" => "ખંભાલિડા",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Khamta", "Local Name" => "ખામટા", "Sub District" => "Paddhari"],
            [
                "Name" => "Khandadhar",
                "Local Name" => "ખંડાધર",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Khandheri",
                "Local Name" => "ખાંધેરી",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Kharachia",
                "Local Name" => "ખારાચિયા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Kharachiya",
                "Local Name" => "ખારાચિયા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Kharachiya",
                "Local Name" => "ખારાચિયા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Kharachiya Jam",
                "Local Name" => "ખારચીયા જામ",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Kharachiya Jas",
                "Local Name" => "ખારાચિયા જસ",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Khareda",
                "Local Name" => "ખારેડા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Khatli",
                "Local Name" => "ખાટલી",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Kherdi", "Local Name" => "ખેરડી", "Sub District" => "Rajkot"],
            [
                "Name" => "Khijadiya",
                "Local Name" => "ખીજાડિયા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Khijadiya Moj",
                "Local Name" => "ખીજડિયા મોજ",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Khijadiya Mota",
                "Local Name" => "ખીજાડિયા મોટા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Khijadiya Nana",
                "Local Name" => "ખીજાડિયા નાના",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Khirsara",
                "Local Name" => "ખીરસરા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Khirsara",
                "Local Name" => "ખીરસરા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Khirsara (Ranmalji)",
                "Local Name" => "ખીરસરા (રણમલજી)",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Khodapipar",
                "Local Name" => "ખોડાપીપર",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Khokhadadad",
                "Local Name" => "ખોખડાદાદ",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Khokhri",
                "Local Name" => "ખોખરી",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Khokhri",
                "Local Name" => "ખોખરી",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Khorana", "Local Name" => "ખોરાણા", "Sub District" => "Rajkot"],
            [
                "Name" => "Kolithad",
                "Local Name" => "કોલિથડ",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Kolki", "Local Name" => "કોલ્કી", "Sub District" => "Upleta"],
            ["Name" => "Kotda", "Local Name" => "કોટડા", "Sub District" => "Vinchhiya"],
            [
                "Name" => "Kotda Sangani",
                "Local Name" => "કોટડા સાંગાણી",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Kotha Pipaliya",
                "Local Name" => "કોઠા પીપળીયા",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Kotharia (Ct)",
                "Local Name" => "કોઠારિયા (સીટી)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Kothariya",
                "Local Name" => "કોઠારિયા",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Kothi", "Local Name" => "કોઠી", "Sub District" => "Jasdan"],
            [
                "Name" => "Kuchiyadad",
                "Local Name" => "કુચિયાદાદ",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Kundani", "Local Name" => "કુંદની", "Sub District" => "Jasdan"],
            [
                "Name" => "Kundhech",
                "Local Name" => "કુંધેચ",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Kuvadva",
                "Local Name" => "કુવાડવા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Lakhapar",
                "Local Name" => "લાખાપર",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Lalavadar",
                "Local Name" => "લાલાવદર",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Lampasari",
                "Local Name" => "લપાસરી",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Lath", "Local Name" => "લાથ", "Sub District" => "Upleta"],
            [
                "Name" => "Laxmi Intala",
                "Local Name" => "લક્ષ્મી ઇંટાળા",
                "Sub District" => "Lodhika",
            ],
            ["Name" => "Lilakha", "Local Name" => "લીલાખા", "Sub District" => "Gondal"],
            [
                "Name" => "Lilapur",
                "Local Name" => "લીલાપુર",
                "Sub District" => "Jasdan",
            ],
            ["Name" => "Lodhida", "Local Name" => "લોધિડા", "Sub District" => "Rajkot"],
            [
                "Name" => "Lodhika",
                "Local Name" => "લોધિકા",
                "Sub District" => "Lodhika",
            ],
            ["Name" => "Lothada", "Local Name" => "લોથાડા", "Sub District" => "Rajkot"],
            [
                "Name" => "Lunagara",
                "Local Name" => "લુનાગારા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Lunagiri",
                "Local Name" => "લુણાગિરી",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Lunivav",
                "Local Name" => "લુનિવાવ",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Madava", "Local Name" => "મડાવા", "Sub District" => "Jasdan"],
            [
                "Name" => "Madhapar (Og)",
                "Local Name" => "માધાપર (ઓગ)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Madhavipur",
                "Local Name" => "માધવીપુર",
                "Sub District" => "Jasdan",
            ],
            ["Name" => "Madhda", "Local Name" => "મઢડા", "Sub District" => "Jasdan"],
            [
                "Name" => "Magharvada",
                "Local Name" => "મઘરવાડા",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Mahika", "Local Name" => "મહિકા", "Sub District" => "Rajkot"],
            [
                "Name" => "Mahika Mota",
                "Local Name" => "મહિકા મોટા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Mahika Nana",
                "Local Name" => "મહિકા નાના",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Makanpar", "Local Name" => "મકનપર", "Sub District" => "Rajkot"],
            [
                "Name" => "Makhavad",
                "Local Name" => "મખાવડ",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Makhiyala",
                "Local Name" => "માળિયાલા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Maliyasan",
                "Local Name" => "માલિયાસન",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Mandankundla",
                "Local Name" => "મંડનકુંડલા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Mandlikpur",
                "Local Name" => "માંડલીકપુર",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Manekvada",
                "Local Name" => "માણેકવાડા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Manharpur (Og)",
                "Local Name" => "મનહરપુર (ઓગ)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Masitala",
                "Local Name" => "મસીતાલા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Matravad Juna",
                "Local Name" => "માતૃવાદ જુના",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Matravad Nava",
                "Local Name" => "માતૃવાદ નાવા",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Mavdi", "Local Name" => "માવડી", "Sub District" => "Rajkot"],
            [
                "Name" => "Meghavad",
                "Local Name" => "મેઘવડ",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Meghpar", "Local Name" => "મેઘપર", "Sub District" => "Jasdan"],
            [
                "Name" => "Mekhatimbi",
                "Local Name" => "મેખાટીંબી",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Meli Majethi",
                "Local Name" => "મેલી મજેઠી",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Mervadar",
                "Local Name" => "મેરવાડર",
                "Sub District" => "Upleta",
            ],
            ["Name" => "Mespar", "Local Name" => "મેસપર", "Sub District" => "Gondal"],
            [
                "Name" => "Mesvada",
                "Local Name" => "મેસવાડા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Meta Khambhaliya",
                "Local Name" => "મેટા ખંભાળિયા",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Metoda", "Local Name" => "મેટોડા", "Sub District" => "Lodhika"],
            [
                "Name" => "Metoda",
                "Local Name" => "મેટોડા",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Mevasa", "Local Name" => "મેવાસા", "Sub District" => "Jetpur"],
            [
                "Name" => "Modhuka",
                "Local Name" => "મોધુકા",
                "Sub District" => "Vinchhiya",
            ],
            ["Name" => "Mojira", "Local Name" => "મોજીરા", "Sub District" => "Upleta"],
            ["Name" => "Monpar", "Local Name" => "મોનપાર", "Sub District" => "Jetpur"],
            [
                "Name" => "Mota Bhadra",
                "Local Name" => "મોટા ભદ્ર",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Mota Gundala",
                "Local Name" => "મોટા ગુંદાળા ",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Mota Hadmatiya",
                "Local Name" => "મોટા હડમતીયા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Mota Mandava",
                "Local Name" => "મોટા માંડવા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Mota Matra",
                "Local Name" => "મોટા માત્રા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Mota Mava (Og)",
                "Local Name" => "મોટા માવા (ઓગ)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Mota Sakhpar",
                "Local Name" => "મોટા સખપર",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Motavada",
                "Local Name" => "મોટાવાડા",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Moti Khilori",
                "Local Name" => "મોટી ખિલોરી",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Moti Lakhavad",
                "Local Name" => "મોટી લાખાવડ",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Moti Marad",
                "Local Name" => "મોટી મારડ",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Moti Parabdi",
                "Local Name" => "મોટી પરબદી",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Moti Vavdi",
                "Local Name" => "મોટી વાવડી",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Moviya",
                "Local Name" => "મોવિયા",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Moviya", "Local Name" => "મોવિયા", "Sub District" => "Gondal"],
            [
                "Name" => "Mungavavdi",
                "Local Name" => "મુંગાવાવડી",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Munjka (Og)",
                "Local Name" => "મુંજકા (ઓગ)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Murakhada",
                "Local Name" => "મુરાખાડા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Nadhu Pipaliya",
                "Local Name" => "નાધુ પીપળીયા",
                "Sub District" => "Lodhika",
            ],
            ["Name" => "Nagadka", "Local Name" => "નાગડકા", "Sub District" => "Gondal"],
            [
                "Name" => "Nagalkhada",
                "Local Name" => "નાગલખાડા",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Nagalpar",
                "Local Name" => "નાગલપર",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Nagar Pipaliya",
                "Local Name" => "નાગર પીપળીયા",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Nagvadar",
                "Local Name" => "નાગવદર",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Nakaravadi",
                "Local Name" => "નાકરાવડી",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Nana Mandava",
                "Local Name" => "નાના માંડવ",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Nana Matra",
                "Local Name" => "નાના માત્રા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Nana Mauva",
                "Local Name" => "નાના મૌવા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Nana Sakhpar",
                "Local Name" => "નાના સખપર",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Nanavada",
                "Local Name" => "નાનાવડા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Nani Lakhavad",
                "Local Name" => "નાની લખાવડ",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Nani Marad",
                "Local Name" => "નાની મારડ",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Nani Parabdi",
                "Local Name" => "નાની પરબદી",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Nani Vavdi",
                "Local Name" => "નાની વાવડી",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Naranka",
                "Local Name" => "નારંકા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Naranka",
                "Local Name" => "નારંકા",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Navagadh", "Local Name" => "નવાગઢ", "Sub District" => "Jetpur"],
            ["Name" => "Navagam", "Local Name" => "નવાગામ", "Sub District" => "Jasdan"],
            ["Name" => "Navagam", "Local Name" => "નવાગામ", "Sub District" => "Rajkot"],
            ["Name" => "Navagam", "Local Name" => "નવાગામ", "Sub District" => "Gondal"],
            [
                "Name" => "Navagam (Bamanbore)",
                "Local Name" => "નવાગામ (બામણબોર)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Navapara",
                "Local Name" => "નવાપારા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Nava Rajpipla",
                "Local Name" => "નવા રાજપીપળા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Navi Mengani",
                "Local Name" => "નવી મેંગાની",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Navi Sankali",
                "Local Name" => "નવી સંકાલી",
                "Sub District" => "Jetpur",
            ],
            ["Name" => "Nilakha", "Local Name" => "નીલખા", "Sub District" => "Upleta"],
            [
                "Name" => "Noghanchora",
                "Local Name" => "નોઘાંચોરા",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Nyara", "Local Name" => "ન્યારા", "Sub District" => "Paddhari"],
            ["Name" => "Ori", "Local Name" => "ઓરી", "Sub District" => "Vinchhiya"],
            [
                "Name" => "Padariya",
                "Local Name" => "પાદરિયા",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Padasan", "Local Name" => "પડાસણ", "Sub District" => "Rajkot"],
            [
                "Name" => "Padavala",
                "Local Name" => "પડાવલા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Padavala",
                "Local Name" => "પડાવલા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Paddhari (Ct)",
                "Local Name" => "પડધરી (સીટી)",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Padvala", "Local Name" => "પડવાલા", "Sub District" => "Upleta"],
            ["Name" => "Pal", "Local Name" => "પાલ", "Sub District" => "Lodhika"],
            [
                "Name" => "Pambhar Intala",
                "Local Name" => "પાંભર ઇન્ટાલા",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Panchavada",
                "Local Name" => "પાંચવડા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Panchiyavadar",
                "Local Name" => "પાંચીયાવદર",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Panchpipla",
                "Local Name" => "પાંચપીપળા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Panchtalavda",
                "Local Name" => "પાંચતલાવડા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Paneli Moti",
                "Local Name" => "પાનેલી મોતી",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Para Pipaliya",
                "Local Name" => "પરા પીપળીયા",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Pardi", "Local Name" => "પારડી", "Sub District" => "Lodhika"],
            [
                "Name" => "Parevala",
                "Local Name" => "પારેવાળા ",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Parewala",
                "Local Name" => "પારેવાળા ",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Patanvav",
                "Local Name" => "પાટણવાવ",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Patidad",
                "Local Name" => "પાટીદાદ",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Patiyali",
                "Local Name" => "પટિયાલી",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Patiyali",
                "Local Name" => "પટિયાલી",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Patkhilori",
                "Local Name" => "પાટખિલોરી",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Pedhla", "Local Name" => "પેઢલા", "Sub District" => "Jetpur"],
            [
                "Name" => "Pipaliya",
                "Local Name" => "પીપળીયા",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Pipaliya",
                "Local Name" => "પીપળીયા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Pipaliya",
                "Local Name" => "પીપળીયા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Pipaliya Agency",
                "Local Name" => "પીપળીયા એજેન્સી",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Pipaliya Karmal",
                "Local Name" => "પીપલિયા કરમાલ",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Pipaliya Maljibhi",
                "Local Name" => "પીપળીયા માલજીભી",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Pipaliya Pal",
                "Local Name" => "પીપળીયા પાલ",
                "Sub District" => "Lodhika",
            ],
            ["Name" => "Pipalva", "Local Name" => "પીપલવા", "Sub District" => "Jetpur"],
            [
                "Name" => "Pipardi",
                "Local Name" => "પીપરડી",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Pipardi",
                "Local Name" => "પીપરડી",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Pipardi",
                "Local Name" => "પીપરડી",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Piplana",
                "Local Name" => "પીપલાણા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Pithadiya",
                "Local Name" => "પીઠાડિયા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Polarpar",
                "Local Name" => "પોલરપાર",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Pransla",
                "Local Name" => "પ્રાંસલા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Pratappur",
                "Local Name" => "પ્રતાપપુર",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Premgadh",
                "Local Name" => "પ્રેમગઢ",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Rabarika",
                "Local Name" => "રબારિકા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Rabarika",
                "Local Name" => "રબારિકા",
                "Sub District" => "Upleta",
            ],
            ["Name" => "Radad", "Local Name" => "રાદાદ", "Sub District" => "Paddhari"],
            ["Name" => "Rafala", "Local Name" => "રફાલા", "Sub District" => "Rajkot"],
            ["Name" => "Raiya", "Local Name" => "રૈયા", "Sub District" => "Rajkot"],
            [
                "Name" => "Raja Vadla Jam",
                "Local Name" => "રાજાવડલા જામ",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Rajavadla Jas",
                "Local Name" => "રાજાવડલા જસ",
                "Sub District" => "Jasdan",
            ],
            ["Name" => "Rajgadh", "Local Name" => "રાજગઢ", "Sub District" => "Rajkot"],
            [
                "Name" => "Rajgadh",
                "Local Name" => "રાજગઢ",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Rajkot", "Local Name" => "રાજકોટ", "Sub District" => "Rajkot"],
            [
                "Name" => "Rajpara",
                "Local Name" => "રાજપરા",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Rajpara", "Local Name" => "રાજપરા", "Sub District" => "Upleta"],
            [
                "Name" => "Rajpara",
                "Local Name" => "રાજપરા",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Ramaliya",
                "Local Name" => "રામલિયા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Ramnagar",
                "Local Name" => "રામનગર",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Ramod",
                "Local Name" => "રામોદ",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Rampar",
                "Local Name" => "રામપર",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Rampara", "Local Name" => "રામપરા", "Sub District" => "Rajkot"],
            [
                "Name" => "Rampara",
                "Local Name" => "રામપરા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Rampara Beti",
                "Local Name" => "રામપરા બેટી",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Rampara (Suliya)",
                "Local Name" => "રામપરા (સુલિયા)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Rampar Mota",
                "Local Name" => "રામપર મોટા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Rampar Pati",
                "Local Name" => "રામપર પાટી",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Rangpar",
                "Local Name" => "રંગપર",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Rangpar",
                "Local Name" => "રંગપર",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Raningpar",
                "Local Name" => "રાનિંગપર",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Ranjitgadh",
                "Local Name" => "રણજીતગઢ",
                "Sub District" => "Jasdan",
            ],
            ["Name" => "Ranpar", "Local Name" => "રાણપર", "Sub District" => "Rajkot"],
            [
                "Name" => "Ranparda",
                "Local Name" => "રાણપર્ડા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Ransiki",
                "Local Name" => "રાંસિકી",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Rataiya", "Local Name" => "રતૈયા", "Sub District" => "Lodhika"],
            [
                "Name" => "Ratanpar",
                "Local Name" => "રતનપર",
                "Sub District" => "Lodhika",
            ],
            ["Name" => "Ratanpar", "Local Name" => "રતનપર", "Sub District" => "Rajkot"],
            ["Name" => "Ravki", "Local Name" => "રાવકી", "Sub District" => "Lodhika"],
            ["Name" => "Ravna", "Local Name" => "રવના", "Sub District" => "Gondal"],
            [
                "Name" => "Raydi",
                "Local Name" => "રાયડી",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Reshamdi Galol",
                "Local Name" => "રેશમદી ગાલોલ",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Revaniya",
                "Local Name" => "રેવાનીયા",
                "Sub District" => "Vinchhiya",
            ],
            ["Name" => "Rib", "Local Name" => "રીબ", "Sub District" => "Gondal"],
            ["Name" => "Ribda", "Local Name" => "રીબડા", "Sub District" => "Gondal"],
            [
                "Name" => "Rodhel",
                "Local Name" => "રોધેલ",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Rojiya",
                "Local Name" => "રોજિયા",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Ronki", "Local Name" => "રોંકી", "Sub District" => "Rajkot"],
            [
                "Name" => "Rupavati",
                "Local Name" => "રૂપાવટી",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Rupavati",
                "Local Name" => "રૂપાવટી",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Rupavati",
                "Local Name" => "રૂપાવટી",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Rupavati",
                "Local Name" => "રૂપાવટી",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Sagaliya Nana",
                "Local Name" => "સગલિયા નાના",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Sajadiali Lili",
                "Local Name" => "સાજડીયાળી  લિલી",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Sajadiali Suki",
                "Local Name" => "સાજડીયાળી  સુકી",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Sajadiyali",
                "Local Name" => "સાજડીયાળી",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Sajadiyali",
                "Local Name" => "સાજડીયાળી",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Sajdiyali",
                "Local Name" => "સાજડીયાળી",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Sal Pipaliya",
                "Local Name" => "સાલ પીપલિયા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Samadhiyala",
                "Local Name" => "સમધિયાળા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Samadhiyala",
                "Local Name" => "સમધિયાળા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Samadhiyala",
                "Local Name" => "સમધિયાળા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Sanala",
                "Local Name" => "સનાલા",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Sanala",
                "Local Name" => "સનાલા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Sanali",
                "Local Name" => "સનાલી",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Sanathali",
                "Local Name" => "સાણથલી ",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Sandhavaya",
                "Local Name" => "સંધવાય",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Sanganva",
                "Local Name" => "સાંગણવા",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Sanosara",
                "Local Name" => "સનોસરા",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Sar", "Local Name" => "સાર", "Sub District" => "Rajkot"],
            [
                "Name" => "Sarapdad",
                "Local Name" => "સારાપદાદ",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Sardhar", "Local Name" => "સરધાર", "Sub District" => "Rajkot"],
            [
                "Name" => "Sardharpur",
                "Local Name" => "સરધારપુર",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Sartanpar",
                "Local Name" => "સરતાનપર",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Satapar",
                "Local Name" => "સતાપર",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Satda", "Local Name" => "સાતદા", "Sub District" => "Rajkot"],
            [
                "Name" => "Satudad",
                "Local Name" => "સાતુદાદ",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Satvadi", "Local Name" => "સાતવડી", "Sub District" => "Upleta"],
            ["Name" => "Saypar", "Local Name" => "સાયપર", "Sub District" => "Rajkot"],
            ["Name" => "Seluka", "Local Name" => "સેલુકા", "Sub District" => "Jetpur"],
            [
                "Name" => "Sevantra",
                "Local Name" => "સેવાન્ત્રા",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Shapur (Ct)",
                "Local Name" => "શાપુર (સીટી)",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Shemla", "Local Name" => "શેમલા", "Sub District" => "Gondal"],
            [
                "Name" => "Shishak",
                "Local Name" => "શિશક",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Shivrajgadh",
                "Local Name" => "શિવરાજગઢ",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Shivrajpur",
                "Local Name" => "શિવરાજપુર",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Shrinathgadh",
                "Local Name" => "શ્રીનાથગઢ",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Sindhavadar",
                "Local Name" => "સિંધાવદર",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Sodvadar",
                "Local Name" => "સોડવદર",
                "Sub District" => "Jamkandorna",
            ],
            ["Name" => "Sokhada", "Local Name" => "સોખડા", "Sub District" => "Rajkot"],
            [
                "Name" => "Soliya",
                "Local Name" => "સોલિયા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Somalpar",
                "Local Name" => "સોમલપર",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Som Pipaliya",
                "Local Name" => "સોમ પીપળીયા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Station Vavdi",
                "Local Name" => "સ્ટેશન વાવડી",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Sultanpur",
                "Local Name" => "સુલતાનપુર",
                "Sub District" => "Gondal",
            ],
            ["Name" => "Supedi", "Local Name" => "સુપેદી", "Sub District" => "Dhoraji"],
            ["Name" => "Suvag", "Local Name" => "સુવાગ", "Sub District" => "Paddhari"],
            [
                "Name" => "Talgana",
                "Local Name" => "તાલગાના",
                "Sub District" => "Upleta",
            ],
            ["Name" => "Tanasva", "Local Name" => "તનાસ્વ", "Sub District" => "Upleta"],
            [
                "Name" => "Taravada",
                "Local Name" => "તારાવડા",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Taravda",
                "Local Name" => "તરવડા",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Targhadiya",
                "Local Name" => "તારઘડિયા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Targhari",
                "Local Name" => "તારઘરી",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Tarkasar",
                "Local Name" => "તારકાસર",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Thana Galol",
                "Local Name" => "થાણા ગાલોલ",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Thebachda",
                "Local Name" => "થેબાચડા",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Thorala",
                "Local Name" => "થોરાળા ",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Thorala",
                "Local Name" => "થોરાળા ",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Thorala",
                "Local Name" => "થોરાળા ",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Thordi",
                "Local Name" => "થોરડી ",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Thordi",
                "Local Name" => "થોરડી ",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Thoriyali",
                "Local Name" => "થોરિયાલી",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Thoriyali",
                "Local Name" => "થોરિયાલી",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Timbadi Jam",
                "Local Name" => "ટિમ્બાડી જામ",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Toraniya",
                "Local Name" => "તોરાનિયા",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Trakuda",
                "Local Name" => "ત્રાકુડા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Udakiya",
                "Local Name" => "ઉડાકિયા",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Ujala",
                "Local Name" => "ઉજાલા",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Ukarda",
                "Local Name" => "ઉકાર્ડા",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Umarkot",
                "Local Name" => "ઉમરકોટ",
                "Sub District" => "Dhoraji",
            ],
            ["Name" => "Umrali", "Local Name" => "ઉમરાલી", "Sub District" => "Rajkot"],
            ["Name" => "Umrali", "Local Name" => "ઉમરાલી", "Sub District" => "Jetpur"],
            [
                "Name" => "Umvada Mota",
                "Local Name" => "ઉમવાડા મોટા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Umvada Nana",
                "Local Name" => "ઉમવાડા નાના",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Und Khijadiya",
                "Local Name" => "ઉંડ ખીજાડિયા",
                "Sub District" => "Lodhika",
            ],
            ["Name" => "Upleta", "Local Name" => "ઉપલેટા", "Sub District" => "Upleta"],
            ["Name" => "Vachhra", "Local Name" => "વાછરા", "Sub District" => "Gondal"],
            [
                "Name" => "Vachli Ghodi",
                "Local Name" => "વાચલી ઘોડી",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Vadali", "Local Name" => "વડાલી", "Sub District" => "Rajkot"],
            ["Name" => "Vadali", "Local Name" => "વડાલી", "Sub District" => "Upleta"],
            [
                "Name" => "Vadasada",
                "Local Name" => "વડસાડા",
                "Sub District" => "Jetpur",
            ],
            [
                "Name" => "Vadekhan",
                "Local Name" => "વાડેખાન",
                "Sub District" => "Upleta",
            ],
            [
                "Name" => "Vadipara",
                "Local Name" => "વાડીપારા",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Vadiya",
                "Local Name" => "વાડિયા",
                "Sub District" => "Kotda Sangani",
            ],
            ["Name" => "Vadla", "Local Name" => "વડલા", "Sub District" => "Upleta"],
            ["Name" => "Vadod", "Local Name" => "વડોદ", "Sub District" => "Jasdan"],
            [
                "Name" => "Vadodar",
                "Local Name" => "વડોદરા",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Vagudad",
                "Local Name" => "વાગુદાદ",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Vajdi Gadh",
                "Local Name" => "વાજડી ગઢ",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Vajdi (Vad)",
                "Local Name" => "વાજડી (વડ)",
                "Sub District" => "Lodhika",
            ],
            [
                "Name" => "Vajdi (Virda)",
                "Local Name" => "વાજડી (વિરદા)",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Valadhari",
                "Local Name" => "વલધારી",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Valadungra",
                "Local Name" => "વાલાડુંગ્રા",
                "Sub District" => "Jetpur",
            ],
            ["Name" => "Vanala", "Local Name" => "વનલા", "Sub District" => "Vinchhiya"],
            [
                "Name" => "Vangadhara",
                "Local Name" => "વાંગધરા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Vankvad",
                "Local Name" => "વાંકવાડ",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Vanpari",
                "Local Name" => "વનપરી",
                "Sub District" => "Paddhari",
            ],
            ["Name" => "Vanthali", "Local Name" => "વંથલી", "Sub District" => "Gondal"],
            [
                "Name" => "Varjang Jalia",
                "Local Name" => "વરજાંગ જાલિયા",
                "Sub District" => "Upleta",
            ],
            ["Name" => "Vasavad", "Local Name" => "વાસાવડ", "Sub District" => "Gondal"],
            [
                "Name" => "Vavdi",
                "Local Name" => "વાવડી",
                "Sub District" => "Jamkandorna",
            ],
            [
                "Name" => "Vavdi (Og)",
                "Local Name" => "વાવડી (ઓગ)",
                "Sub District" => "Rajkot",
            ],
            ["Name" => "Vegdi", "Local Name" => "વેગડી", "Sub District" => "Dhoraji"],
            ["Name" => "Vejagam", "Local Name" => "વેજગામ", "Sub District" => "Gondal"],
            ["Name" => "Vejagam", "Local Name" => "વેજગામ", "Sub District" => "Rajkot"],
            ["Name" => "Vekri", "Local Name" => "વેકરી", "Sub District" => "Gondal"],
            [
                "Name" => "Velariya",
                "Local Name" => "વેલારિયા",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Veraval Bhadla",
                "Local Name" => "વેરાવળ ભાડલા",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Veraval Bhadli",
                "Local Name" => "વેરાવળ ભાડલી",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Veraval (Ct)",
                "Local Name" => "વેરાવળ (સીટી)",
                "Sub District" => "Kotda Sangani",
            ],
            [
                "Name" => "Veraval Sanathali",
                "Local Name" => "વેરાવળ સાણથલી ",
                "Sub District" => "Jasdan",
            ],
            [
                "Name" => "Vijaynagar",
                "Local Name" => "વિજયનગર",
                "Sub District" => "Rajkot",
            ],
            [
                "Name" => "Vinchhiya",
                "Local Name" => "વિંચિયા",
                "Sub District" => "Vinchhiya",
            ],
            [
                "Name" => "Vinzivad",
                "Local Name" => "વિંઝીવાડ",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Virnagar",
                "Local Name" => "વીરનગર",
                "Sub District" => "Jasdan",
            ],
            ["Name" => "Virpur", "Local Name" => "વીરપુર", "Sub District" => "Jasdan"],
            ["Name" => "Virpur", "Local Name" => "વીરપુર", "Sub District" => "Jetpur"],
            ["Name" => "Virva", "Local Name" => "વિરવા", "Sub District" => "Lodhika"],
            [
                "Name" => "Visaman",
                "Local Name" => "વિસામન",
                "Sub District" => "Paddhari",
            ],
            [
                "Name" => "Vorakotda",
                "Local Name" => "વોરાકોટડા",
                "Sub District" => "Gondal",
            ],
            [
                "Name" => "Zanzmer",
                "Local Name" => "ઝાંઝમેર",
                "Sub District" => "Dhoraji",
            ],
            [
                "Name" => "Zundala",
                "Local Name" => "ઝુંડાલા",
                "Sub District" => "Jasdan",
            ],
        ];


        foreach ($villages as $data) {
            $subDistrict = SubDistrict::where('name', $data['Sub District'])->first();


            Village::create([
                'name' => $data['Name'],
                'local_name' => $data['Local Name'],
                'sub_district_id' => $subDistrict->id,
                'sub_district_code' => $subDistrict->sub_district_code,
                'district_id' => $subDistrict->district_id,
                'district_code' => $subDistrict->district?->district_code,
                'state_id' => $subDistrict->district?->state_id ?? 1,
                'state_code' => $subDistrict->district?->state?->state_code ?? '24',
                'country_id' => 1,
            ]);
        }
    }
}
